name: upgrade-actions
on:
  schedule:
    - cron: 37 1 * * 1
  workflow_dispatch: {}
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  pin:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup TSCCR helper
        uses: hashicorp/setup-tsccr-helper@v1
        with:
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
      - name: Pin all workflows based on TSCCR
        run: tsccr-helper gha update -latest .
        env:
          GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW_TOKEN }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          branch: auto/upgrade-actions
          base: main
          commit-message: "chore(deps): pin trusted workflows based on HashiCorp TSCCR"
          title: "chore(deps): pin trusted workflows based on HashiCorp TSCCR"
          body: "This PR upgrades all GitHub Actions to newer versions so long as they have been verified by HashiCorp's security team."
          labels: dependencies,automerge,auto-approve
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
          author: hashicorp-tsccr[bot] <hashicorp-tsccr[bot]@users.noreply.github.com>
          committer: hashicorp-tsccr[bot] <hashicorp-tsccr[bot]@users.noreply.github.com>
          signoff: true
          delete-branch: true
